name: nathan-king-website
static_sites:
- name: website
  source_dir: /
  github:
    repo: nathan-a-king/website
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: build
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  environment_slug: node-js
