name: nathan-king-website
services:
- name: web
  source_dir: /
  github:
    repo: nathan-a-king/website
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  run_command: npx serve -s build -l 8080
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
